name: flutter_map_tile_caching
description: Plugin for 'flutter_map' providing advanced caching functionality,
  with ability to download map regions for offline use.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 5.0.0-dev.2
repository: https://github.com/JaffaKetchup/flutter_map_tile_caching
documentation: https://fmtc.jaffaketchup.dev

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  background_fetch: ^1.1.0
  battery_info: ^1.1.1
  bezier: ^1.2.0
  collection: ^1.16.0
  connectivity_plus: ^2.3.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.4.1
  
  flutter_map:
    git:
      url: https://github.com/fleaflet/flutter_map
      ref: 9dcdfde4b1a7f85ed0c077dd01fed2c6c139cf3d
  
  http: ^0.13.3
  ini: ^2.1.0
  latlong2: ^0.8.0
  meta: ^1.7.0
  path: ^1.8.0
  path_provider: ^2.0.7
  permission_handler: ^10.0.0
  queue: ^3.1.0+1
  stream_transform: ^2.0.0
  vector_math: ^2.1.1
  watcher: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: null
